// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDunjgAr06RPlDdlIU1wfPdcuVXBk84LHM',
    appId: '1:307862214822:web:e0ca7fa945020ec35bbc67',
    messagingSenderId: '307862214822',
    projectId: 'energy-service-portal-a7636',
    authDomain: 'energy-service-portal-a7636.firebaseapp.com',
    storageBucket: 'energy-service-portal-a7636.firebasestorage.app',
    measurementId: 'G-D5JJJ6VWVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDylExJGmrtLAIuMwUXnJxQzxJ896wJ0i4',
    appId: '1:307862214822:android:07594df0c64a2bfe5bbc67',
    messagingSenderId: '307862214822',
    projectId: 'energy-service-portal-a7636',
    storageBucket: 'energy-service-portal-a7636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7EnTS9vUYD5WgJkFzZhOPbChWYgEq8jU',
    appId: '1:307862214822:ios:28e499bffdf7b34a5bbc67',
    messagingSenderId: '307862214822',
    projectId: 'energy-service-portal-a7636',
    storageBucket: 'energy-service-portal-a7636.firebasestorage.app',
    iosBundleId: 'com.example.licencesApplication',
  );
}
