// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTagqWobW0DZm2bILicQr9ZsfrWgvWAaE',
    appId: '1:770049951032:web:d5db6af5efd6fc86deadcd',
    messagingSenderId: '770049951032',
    projectId: 'liceans-3ebf2',
    authDomain: 'liceans-3ebf2.firebaseapp.com',
    storageBucket: 'liceans-3ebf2.firebasestorage.app',
    measurementId: 'G-DZ32EKB5DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HYmqH5-VbAsRpcEdQMs3Nj9MJCXcRno',
    appId: '1:770049951032:android:13a2937967daecccdeadcd',
    messagingSenderId: '770049951032',
    projectId: 'liceans-3ebf2',
    storageBucket: 'liceans-3ebf2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5p8sAMMjrzb3_wwZrO1GKKw64NyIMEa0',
    appId: '1:770049951032:ios:c970d4fe1d47db64deadcd',
    messagingSenderId: '770049951032',
    projectId: 'liceans-3ebf2',
    storageBucket: 'liceans-3ebf2.firebasestorage.app',
    iosBundleId: 'com.example.licencesApplication',
  );
}
